### ISSUE TITLE
New parameter file format to be compatible with Omicron development version

### ISSUE THREAD

**Issue by jlmciver** [duncanmmacleod/pyomicron#1]
If the development version is detected, parameter files should take the format where: 

PARAMETER CHUNKDURATION       304
PARAMETER SEGMENTDURATION     64
PARAMETER OVERLAPDURATION     4

now writes:

PARAMETER  TIMING    64  4
PARAMETER  PSDLENGTH    304

**Comment by jlmciver** [comment]
This has been tested to work.

**Comment by duncanmmacleod** [comment]
@jlmciver: this code has not been pushed, the issue should remain open until then.
